"""Add grade_point and pass_fail to StudentCourseGrade

Revision ID: 0528bde5114b
Revises: 7120c7262db7
Create Date: 2026-02-02 16:23:05.441854

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0528bde5114b'
down_revision = '7120c7262db7'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('student_course_grade', schema=None) as batch_op:
        batch_op.add_column(sa.Column('grade_point', sa.Float(), nullable=True))
        batch_op.add_column(sa.Column('pass_fail', sa.String(length=10), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('student_course_grade', schema=None) as batch_op:
        batch_op.drop_column('pass_fail')
        batch_op.drop_column('grade_point')

    # ### end Alembic commands ###
